from fastapi import FastAPI, UploadFile, Query
from fastapi.staticfiles import StaticFiles
from fastapi.responses import StreamingResponse
import crop
from typing import Annotated
from pydantic import BaseModel

app = FastAPI()
crop_session = crop.CropSession()

app.mount("/static", StaticFiles(directory="static"), name="static")

@app.get("/")
def read_root():
    return {"Hello": "World"}


@app.get("/items/{item_id}")
def read_item(item_id: int, q: str | None = None):
    return {"item_id": item_id, "q": q}

@app.post("/crop/load_video",
        responses = {
            200: {
                "content": {"image/png": {}}
            }
        },

        # Prevent FastAPI from adding "application/json" as an additional
        # response media type in the autogenerated OpenAPI specification.
        # https://github.com/tiangolo/fastapi/issues/3258
        response_class=StreamingResponse
        )
async def crop_load_video(video_file: UploadFile):
    crop_session.load_video_file(video_file)
    print(crop_session.first_frame)
    #return {"filename": video_file.filename}
    return StreamingResponse(content=crop_session.first_frame, media_type="image/jpg")

@app.get('/crop/get_frame')
async def get_frame():
    return StreamingResponse(content=crop_session.first_frame, media_type='image/jpg')

@app.get('/crop/click/{x}/{y}')
async def crop_click(x: int, y: int):
    print(x,y)
    crop_session.click(x,y)
    return StreamingResponse(content=crop_session.masks[0], media_type="image/jpg")

class Targets(BaseModel):
    target_list: list[list[int]]

@app.post('/crop/detect_objects')
async def detect_objects(targets: Targets):
    crop_session.generate_masks(targets.target_list)
    return StreamingResponse(content=crop_session.masks[0], media_type="image/jpg")

@app.get('/crop/track')
async def track_objects():
    crop_session.track()
    return crop_session.coords.tolist()

@app.get('/crop/crop/{n_frames}/{size}')
async def crop_video(n_frames: int, size: int):
    crop_session.crop(n_frames, size)